correo_input = "";
cursor_pos = 0;
escribiendo = true;
x_visual = 50;
y_visual = 100;
ancho = 500;
alto = 40;
borrar_delay = 0;
borrar_intervalo = 5; // borrar cada 5 frames mientras se mantiene Backspace
global.input_confirmado = false;
global.idJugador = "";
